import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Anchor, Container, Text, Title, Image } from "@mantine/core";
import { ToDoList } from "./ToDoList";
import { UserDashboard } from "../components/UserDashboard";

const user = "Ben";
const Home: NextPage = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CheckLyst</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {user ? (
          <Container>
            <UserDashboard user={user}></UserDashboard>
          </Container>
        ) : (
          <Container>
            <Title>Welcome</Title>
            <Image
              my="xl"
              src="http://localhost:3000/heroimage.jpeg"
              height={200}
            ></Image>
            <Text my="xl">
              CheckLyst is a free, lightweight, and addictive to-do list
              application. To unlock the power of CheckLyst,{" "}
              <Anchor variant="gradient">Sign up</Anchor> today!
            </Text>
          </Container>
        )}
      </main>
    </div>
  );
};

export default Home;
