import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Container, Text, Title } from "@mantine/core";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cross Off</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Container>
          <Text>Homepage</Text>
        </Container>
      </main>
    </div>
  );
};

export default Home;
