import React from "react";
import { useSession, signIn, signOut } from "next-auth/react";
import Link from "next/link";
import { Button, Container, TextInput, Title } from "@mantine/core";
import styles from "../styles/Home.module.css";
import Head from "next/head";

export default function Login() {
  return (
    <>
      <Head>
        <title>CheckLyst</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <main className={styles.main}>
        <Title>Login</Title>
        <Container m={"xl"}>
          <TextInput label="email"></TextInput>
          <TextInput label="password"></TextInput>
          <Button variant="outline">Login</Button>
        </Container>
      </main>
    </>
  );
}
