import React, { useState } from "react";
import { signIn } from "next-auth/react";
import {
  Anchor,
  Button,
  Container,
  TextInput,
  Title,
  Text,
} from "@mantine/core";
import styles from "../styles/Home.module.css";
import Head from "next/head";
import { getLocationOrigin } from "next/dist/shared/lib/utils";
import { FacebookIcon, GoogleIcon, Logo, LogoVertical, AppleIcon } from "svg";
import { SVGIcon } from "../components/SVGIcon";
import Auth from "../components/Auth";

export default function Login() {
  const [password, setPassword] = useState("");
  const [email, setEmail] = useState("");
  return (
    <>
      <Head>
        <title>CheckLyst</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <main className={styles.main}>
        <Title>Sign In</Title>
        <Auth labelText="sign in"></Auth>
        <Container m={"xl"}>
          <TextInput
            label="email"
            onChange={(e: any) => setEmail(e.target.value)}
          ></TextInput>
          <TextInput
            label="password"
            onChange={(e: any) => setPassword(e.target.value)}
          ></TextInput>
          <Button
            variant="outline"
            onClick={() =>
              signIn("credentials", {
                username: email,
                password: password,
                callbackUrl: getLocationOrigin(),
              })
            }
          >
            Login
          </Button>
        </Container>
      </main>
    </>
  );
}
